# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/vivado/.Xil/Vivado-14900-Victus/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -include C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/mem {
      C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/rom_reader/game_ui_rom_reader.v
      C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/rom_reader/character_object_rom_reader.v
      C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/rom_reader/font_data_rom_reader.v
      C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/object/object_position_controller.v
      C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/object/object_renderer.v
      C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/rom_reader/game_manager_rom_reader.v
      C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/game_display/game_display_renderer.v
      C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/runtime/game_ui_runtime.v
      C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/player/player_position_controller.v
      C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/peripherals/vga_translator.v
      C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/top/clk_div.v
      C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/peripherals/universal_renderer.v
      C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/player/player_renderer.v
      C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/rom_reader/platform_object_rom_reader.v
      C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/runtime/multi_object_trigger_runtime.v
      C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/runtime/multi_object_collider_runtime.v
      C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/runtime/main_game_runtime.v
      C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/game_display/game_display_controller.v
      C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/rom_reader/attack_object_rom_reader.v
      C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/verilog/sources/top/topModule.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top topModule
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/BTCOM/Desktop/0_Project/ChronoForge-FPGA-Engine/vivado/.Xil/Vivado-14900-Victus/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  if { [info exists rt::helper_shm_key] && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $rt::helper_shm_key
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
